version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudretail
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - cloudretail
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - cloudretail

  product-service:
    build: ./product-service
    ports:
      - "8002:8000"
    env_file:
      - ./product-service/.env
    environment:
      DB_HOST: db
      USER_SERVICE_URL: http://user-service:8000
    depends_on:
      - db
    networks:
      - cloudretail

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    env_file:
      - ./order-service/.env
    environment:
      DB_HOST: db
      PRODUCT_SERVICE_URL: http://product-service:8000
      NOTIFICATION_SERVICE_URL: http://notification-service:8000
    depends_on:
      - db
      - product-service
    networks:
      - cloudretail

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8000"
    environment:
      DB_HOST: db
    env_file:
      - ./notification-service/.env
    depends_on:
      - db
    networks:
      - cloudretail

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    environment:
      USER_SERVICE: http://user-service:8000
      PRODUCT_SERVICE: http://product-service:8000
      ORDER_SERVICE: http://order-service:8000
      NOTIFICATION_SERVICE: http://notification-service:8000
    depends_on:
      - user-service
      - product-service
      - order-service
      - notification-service
    networks:
      - cloudretail

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - cloudretail

networks:
  cloudretail:
    driver: bridge

volumes:
  mysql_data:
